#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostartout.sh
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         1
bspc config window_gap           0
bspc config top_padding          0
bspc config bottom_padding       30
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config directional_focus_tightness low

#BSPWM coloring
bspc config normal_border_color		"#000000"
bspc config active_border_color		"#D2A473"
bspc config focused_border_color	"#73D283"
bspc config presel_feedback_color	"#73D2BC"
bspc config urgent_border_color 	"#FFFFFF"


#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Vlc state=fullscreen

#Floating applications
#bspc rule -a URxvt:abc state=floating
bspc rule -a feh state=floating
bspc rule -a Galculator state=floating
bspc rule -a Gcolor3 state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Leafpad state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Xfce4-terminal state=floating
#Tiled applications
bspc rule -a Surf state=tiled

#open applications on specific workspaces
bspc rule -a iceweasel desktop='^1' follow=on
bspc rule -a Oblogout desktop='^1' follow=on
bspc rule -a Termite desktop='^2' state=tiled follow=on
bspc rule -a Gimp desktop='^3'	follow=on
bspc rule -a Gnumeric desktop='^4' follow=on
bspc rule -a qBittorrent desktop='^4' follow=on
bspc rule -a Soffice desktop='^5' follow=on
bspc rule -a Virt-manager desktop='^6' follow=on
bspc rule -a Lxappearance desktop='^7' follow=on
bspc rule -a Hexchat desktop='^7' follow=on
bspc rule -a Arandr desktop='^8' state=floating follow=on
bspc rule -a Thunderbird desktop='^9' follow=on
bspc rule -a KeePassXC desktop='^10' follow=on
bspc rule -a SimpleScreenRecorder desktop='^10'

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
